services:
    db:
        image: mysql:8.0
        command: >
            --default-authentication-plugin=mysql_native_password
        volumes:
            - mysql_data:/var/lib/mysql
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        ports:
            - "3306:3306"

    ceragon-backend:
        build: .
        volumes:
            - .:/app
        ports:
            - "8000:8000"
        depends_on:
            - db
        env_file:
            - .env

volumes:
    mysql_data:
